packages:
  - 'shell'
  - 'storybook'
  - 'libs/*'
  - 'apps/*'
  - 'local/*'
overrides:
  react: 19.2.6
  react-dom: 19.2.6
allowBuilds:
  '@enzedonline/quill-blot-formatter2': false
  canvas: false
  core-js: false
  esbuild: false
  unrs-resolver: false
minimumReleaseAgeExclude:
  - '@biomejs/biome@2.4.16'
  - '@biomejs/cli-darwin-arm64@2.4.16'
  - '@biomejs/cli-darwin-x64@2.4.16'
  - '@biomejs/cli-linux-arm64-musl@2.4.16'
  - '@biomejs/cli-linux-arm64@2.4.16'
  - '@biomejs/cli-linux-x64-musl@2.4.16'
  - '@biomejs/cli-linux-x64@2.4.16'
  - '@biomejs/cli-win32-arm64@2.4.16'
  - '@biomejs/cli-win32-x64@2.4.16'
  - '@typescript/native-preview-darwin-arm64@7.0.0-dev.20260527.1'
  - '@typescript/native-preview-darwin-x64@7.0.0-dev.20260527.1'
  - '@typescript/native-preview-linux-arm64@7.0.0-dev.20260527.1'
  - '@typescript/native-preview-linux-arm@7.0.0-dev.20260527.1'
  - '@typescript/native-preview-linux-x64@7.0.0-dev.20260527.1'
  - '@typescript/native-preview-win32-arm64@7.0.0-dev.20260527.1'
  - '@typescript/native-preview-win32-x64@7.0.0-dev.20260527.1'
  - '@typescript/native-preview@7.0.0-dev.20260527.1'
  - '@symbion/opalui@0.14.10'
