packages:
  - 'shell'
  - 'storybook'
  - 'libs/*'
  - 'apps/*'
  - 'local/*'
overrides:
  react: 19.3.0
  react-dom: 19.3.0
allowBuilds:
  '@enzedonline/quill-blot-formatter2': false
  '@parcel/watcher': true
  canvas: false
  core-js: false
  esbuild: false
  unrs-resolver: false
minimumReleaseAgeExclude:
  - '@symbion/opalui@0.16.0'
