// SPDX-FileCopyrightText: Szilárd Hajba
// SPDX-License-Identifier: LGPL-3.0-or-later

/**
 * Task data structure - simplified for tutorial
 *
 * This demonstrates the minimal data needed for a collaborative todo app.
 * The RTDB library handles all the real-time synchronization automatically.
 */
export interface Task {
	id: string // Unique identifier (auto-generated by RTDB)
	text: string // Task description
	completed: boolean // Completion status
	createdAt: string // ISO 8601 timestamp
}

/**
 * Filter types for displaying tasks
 */
export type TaskFilter = 'all' | 'active' | 'completed'

// vim: ts=4
