// This file is part of the Cloudillo Platform.
// Copyright (C) 2024  Szilárd Hajba
//
// Cloudillo is free software: you can redistribute it and/or modify
// it under the terms of the GNU Lesser General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

/**
 * Task data structure - simplified for tutorial
 *
 * This demonstrates the minimal data needed for a collaborative todo app.
 * The RTDB library handles all the real-time synchronization automatically.
 */
export interface Task {
	id: string // Unique identifier (auto-generated by RTDB)
	text: string // Task description
	completed: boolean // Completion status
	createdAt: string // ISO 8601 timestamp
}

/**
 * Filter types for displaying tasks
 */
export type TaskFilter = 'all' | 'active' | 'completed'

// vim: ts=4
